server:
  port: 9006
spring:
  application:
    name: livegoods-buy-time
  profiles:
    active: mongo
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://192.168.1.4:8761/eureka/